//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hra.Colas.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tv
    {
        public int Id { get; set; }
        public int BloqueId { get; set; }
        public string Denominacion { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Bloque Bloque { get; set; }
    }
}
